# Shared helpers for BasaPOS install payload. Dot-source me.
# PS 5.1-compatible. No profile dependencies.

$script:Distro = "BasaPOS"
$script:Domain = "basapos.local"
$script:BenchPath = "/home/frappe/bench"
$script:LF = [char]10

function Write-BasaLog {
  param([string]$Message)
  $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Message
  # Always write to the debug file (known to work in Inno Setup context)
  if ($env:BASA_DEBUG_FILE) {
    [System.IO.File]::AppendAllText($env:BASA_DEBUG_FILE, $line + $script:LF)
  }
  # Also write to the dedicated log file if available
  if ($env:BASA_LOG_FILE) {
    try { [System.IO.File]::AppendAllText($env:BASA_LOG_FILE, $line + $script:LF) } catch {}
  }
}

function Test-RebootPending {
  if (Test-Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations") { return $true }
  if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending") { return $true }
  return $false
}

function Test-WslInstalled {
  try { & wsl.exe --status 2>$null | Out-Null; return ($LASTEXITCODE -eq 0) } catch { return $false }
}

function Invoke-WslCaptured {
  # wsl.exe writes UTF-16 to stdout; PS mangles it. Re-decode captured bytes.
  param([string[]]$WslArgs)
  $old = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    $out = & wsl.exe @WslArgs 2>$null
    if ($null -eq $out) { return "" }
    return ([System.Text.Encoding]::Unicode.GetString([System.Text.Encoding]::Default.GetBytes(($out -join $script:LF))))
  } finally { $ErrorActionPreference = $old }
}

function Test-DistroPresent {
  param([string]$InstallRoot)   # dir that would contain data\distro\ext4.vhdx
  if ($InstallRoot) {
    $vhd = Join-Path $InstallRoot "data\distro\ext4.vhdx"
    if (Test-Path $vhd) { return $true }
  }
  $text = Invoke-WslCaptured @("--list", "--quiet")
  return ($text -match [regex]::Escape($script:Distro))
}

function Get-SiteUrl {
  param([string]$SettingsFile)
  $domain = $script:Domain
  if ($SettingsFile -and (Test-Path $SettingsFile)) {
    foreach ($line in (Get-Content $SettingsFile)) {
      if ($line -match '^\s*DOMAIN\s*=\s*(.+?)\s*$') { $domain = $Matches[1]; break }
    }
  }
  return "https://$domain"
}

function Test-SiteOnline {
  param([string]$Url)
  try {
    $code = & curl.exe -sk -o NUL -w "%{http_code}" "$Url/api/method/ping" 2>$null
    return ($code -eq "200")
  } catch { return $false }
}

# --- TLS trust ---------------------------------------------------------------
# The appliance generates a per-machine self-signed cert at first boot
# (basapos-firstboot.service). Browsers show "Not secure" unless that exact
# cert is in the Windows trust store. Ensure-TrustedCert exports it from the
# running distro (via \\wsl$, which avoids wsl.exe's UTF-16 stdout mangling)
# and imports it into LocalMachine\Root. Idempotent: when the tracked
# thumbprint is already trusted it does nothing; when the appliance cert
# changed (fresh upgrade re-import regenerates it) it imports the new cert
# and removes the previously tracked one.

function Get-PemThumbprint {
  param([string]$PemPath)
  $text = Get-Content $PemPath -Raw
  $b64 = ($text -replace '-----BEGIN CERTIFICATE-----', '' -replace '-----END CERTIFICATE-----', '' -replace '\s', '')
  $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2(, [Convert]::FromBase64String($b64))
  return $cert.Thumbprint
}

function Ensure-TrustedCert {
  param([Parameter(Mandatory=$true)][string]$InstallRoot)
  try {
    $tlsDir = Join-Path $InstallRoot "config\tls"
    New-Item -ItemType Directory -Force -Path $tlsDir | Out-Null
    $pem = Join-Path $tlsDir "basapos.crt"
    $thumbFile = Join-Path $tlsDir "cert-thumbprint.txt"

    # cert is generated by basapos-firstboot before nginx starts; if the site
    # is reachable it must exist -- guard anyway so callers can run eagerly.
    & wsl.exe -d $script:Distro -u root --exec /bin/test -f /etc/nginx/ssl/basapos.crt 2>$null | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-BasaLog "cert trust: /etc/nginx/ssl/basapos.crt not present yet"; return $false }

    # D17: 9P shares can be slow to serve right after a distro (re)start -
    # retry both share prefixes instead of failing on the first attempt.
    $copied = $false
    foreach ($share in @("\\wsl$\$script:Distro\etc\nginx\ssl\basapos.crt",
                         "\\wsl.localhost\$script:Distro\etc\nginx\ssl\basapos.crt")) {
      for ($i = 1; $i -le 3 -and -not $copied; $i++) {
        try { Copy-Item $share $pem -Force -ErrorAction Stop; $copied = $true } catch { Start-Sleep -Seconds 5 }
      }
      if ($copied) { break }
    }
    if (-not $copied) { Write-BasaLog "cert trust: could not copy cert via wsl`$/wsl.localhost shares"; return $false }
    $thumb = Get-PemThumbprint -PemPath $pem
    if (-not $thumb) { Write-BasaLog "cert trust: could not parse exported cert"; return $false }

    $oldThumb = $null
    if (Test-Path $thumbFile) { $oldThumb = (Get-Content $thumbFile -First 1).Trim() }

    $trusted = $false
    try { if (Get-Item -Path "Cert:\LocalMachine\Root\$thumb" -ErrorAction Stop) { $trusted = $true } } catch {}
    if (-not $trusted) {
      if ($oldThumb -and ($oldThumb -ne $thumb)) {
        try { Remove-Item -Path "Cert:\LocalMachine\Root\$oldThumb" -ErrorAction Stop | Out-Null } catch {}
      }
      $imported = Import-Certificate -FilePath $pem -CertStoreLocation Cert:\LocalMachine\Root
      Set-Content -Path $thumbFile -Value $imported.Thumbprint -Encoding ascii
      Write-BasaLog "cert trust: imported $($imported.Thumbprint) into LocalMachine\Root"
    } else {
      # Already trusted; drop a stale tracked cert (e.g. re-imported out of
      # band or thumbprint file from a previous appliance cert).
      if ($oldThumb -and ($oldThumb -ne $thumb)) {
        try { Remove-Item -Path "Cert:\LocalMachine\Root\$oldThumb" -ErrorAction Stop | Out-Null } catch {}
      }
      Set-Content -Path $thumbFile -Value $thumb -Encoding ascii
    }
    return $true
  } catch {
    Write-BasaLog "cert trust: $($_.Exception.Message)"
    return $false
  }
}

# NOTE: cert removal on uninstall lives INLINE in remove-basapos.ps1 (it must
# not depend on dot-sourcing common.ps1, which may already be deleted by a
# partial uninstall). Keep the thumbprint path in sync:
#   <InstallRoot>\config\tls\cert-thumbprint.txt
